### ISSUE TITLE
sourcemap not generated

### ISSUE THREAD

**Issue by la-yumba** [mzgol/grunt-ng-annotate#18]
I am trying to generate a sourcemap so that my huge file with all the client code can be mapped back to the individual files. My config is:
```
  config.ngAnnotate = {
    options: {
      ngAnnotateOptions: {
        sourcemap: true,
        sourceroot: '/client'
      }
    },
    clientApp: {
      src: config.files.clientApp,
      dest: 'client/dist/app.js'
    }
  };
```
Unfortunately it does not work and no sourcemap indications appear in the produced app.js file
And yet ngAnnotate should support those options....

**Comment by mzgol** [comment]
grunt-ng-annotate 0.9.0 with source map support released (see description in README).

Please report bugs. :)

BTW, the newest grunt-ng-annotate should work on io.js as well as Node.

**Comment by readme42** [comment]
Unfortunately, [this example](https://github.com/mzgol/grunt-ng-annotate/issues/18#issue-49021438) from above still does not work. I need the possibility to use an inFile and will have a look at @la-yumba's solution.

**Comment by mzgol** [comment]
> Unfortunately, this example from above still does not work in 0.9.2.

It's because the example is incorrect. Source map parameters should be put inside the value at the `sourcemap` property, not side by side. Try sth like:
```js
  config.ngAnnotate = {
    options: {
      ngAnnotateOptions: {
        sourcemap: {
          sourceroot: '/client'
        }
      }
    },
    clientApp: {
      src: config.files.clientApp,
      dest: 'client/dist/app.js'
    }
  };
```

As for `inFile`, I should probably write it at https://github.com/mzgol/grunt-ng-annotate/blob/77d8efc8a9fd0c0f7d963701c8301f5f91a13364/tasks/ng-annotate.js#L156 only if it wasn't explicitly defined. PR welcome or I'll get to it within a few weeks. ;)
