### ISSUE TITLE
How can I insert semicolon in between files?

### ISSUE THREAD

**Issue by flipjs** [mzgol/grunt-ng-annotate#22]
When concatenating files, I want to insert a single semicolon in between files/modules, in case of iife that has no semicolon at the end. Thanks.

**Comment by mzgol** [comment]
Thanks for the report! The fix will be in the next grunt-ng-annotate version.

**Comment by flipjs** [comment]
Thank you!

**Comment by areologist** [comment]
This change broke my build after updating grunt-ng-annotate. I run jshint on the output from this task and it doesn't like ";;" and has no option to specifically ignore double semicolons. And while I'm not super opinionated about it, my understanding is that defensive semicolons are not a good practice. 

I'd argue that it should at least be configurable. For example, grunt-contrib-concat has a "separator" option that when set to ";" will insert a defensive semicolon, but by default it doesn't insert anything.

Btw, thank you for maintaining this excellent tool. I am extremely appreciative of your work.

**Comment by areologist** [comment]
I've submitted a pull request that allows for specifying a separator to be inserted between concatenated files.

https://github.com/mzgol/grunt-ng-annotate/pull/28

If this change is accepted it may cause a problem for you flipjs, since the default behavior of grunt-ng-annotate would be no separator.
