### ISSUE TITLE
Is this plugin should work?

### ISSUE THREAD

**Issue by idangozlan** [mzgol/grunt-ng-annotate#29]
I think that i didnt got the idea of this plugin / it is not working as expected..

**test.js**

`
myApp
    .factory('accountService', ['$rootScope', function($rootScope) {
		var obj = {};
        obj.load = function() {
            $http.get('/api/getUser').success(function(data) {
                console.log(data);
            });
        };
	}]);
`

hope that it will add $http and replace "$rootScope" with '$rootScope'. but it's keep file the same.

**grunt task:**
`
ngAnnotate: {
			options: {
				singleQuotes: true,
			},
			myApp: {
				files: {
					'test.js': ['test.js'],
				},
			},
		},
`

**grunt results:**

`Running "ngAnnotate:myApp" (ngAnnotate) task
>> 1 file successfully generated.

Done, without errors.`

**Comment by mzgol** [comment]
This is not how `ng-annotate` works. You need to provide all required parameters to the function yourself, `ng-annotate`'s goal is to add explicit annotations i.e. it changes the following:
```js
myApp
    .factory('accountService', function($http, $rootScope) {
		var obj = {};
        obj.load = function() {
            $http.get('/api/getUser').success(function(data) {
                console.log(data);
            });
        };
	});
```
to:
```js
myApp
    .factory('accountService', ['$http', '$rootScope', function($http, $rootScope) {
		var obj = {};
        obj.load = function() {
            $http.get('/api/getUser').success(function(data) {
                console.log(data);
            });
        };
	}]);
```

P.S. Please wrap multiline blocks in triple backticks with `js` after the opening one, otherwise formatting gets broken. I fixed your comment, you may edit it to see how it's done.
